"""
Convert open-thoughts/OpenThoughts-114k into role-formatted JSONL files.

This is the data pipeline for training a Large Reasoning Model (LRM).

LRM note: OpenThoughts-114k is the recommended dataset for LRM training because:
  - 114k examples across math, science, code, and puzzles (diverse domains)
  - Reasoning traces generated by DeepSeek-R1 (high quality, verified correct)
  - Traces are formatted with <think>...</think> tags already
  - Apache 2.0 license
  - Proven to train capable reasoning models (OpenThinker-7B/32B)

The key difference from a standard conversational dataset (e.g., OASST2) is that
each assistant turn begins with a full chain-of-thought reasoning trace inside
<think>...</think>, followed by the final answer. During training, the model is
supervised on the ENTIRE assistant turn — thinking trace and answer alike.
This teaches the model to reason step-by-step before producing a final answer.

Output schema per line:
{
  "id": str,
  "source": "open-thoughts/OpenThoughts-114k",
  "split": "train" | "val",
  "turns": [{"role": "user"|"assistant", "text": str}, ...],
  "serialized_text": str,        ← includes <think>...</think> intact
  "stats": {
    "char_len": int,
    "has_thinking": bool          ← True if assistant turn contains </think>
  }
}

Design goals:
- Mirror the structure of convert_oasst2_to_jsonl.py for easy comparison.
- Keep <think>...</think> blocks intact in serialized_text.
- Use the same deterministic MD5 train/val split as the OASST2 converter.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

ROLE_USER = "user"
ROLE_ASSISTANT = "assistant"

# The system prompt used in OpenThoughts-114k. Including it during inference
# (via build_chat_prompt's system_text arg) helps the model enter "reasoning mode".
# LRM note: This exact phrasing was part of every training example in the dataset,
# so it acts as a condition that activates the learned thinking behavior.
OPENTHOUGHTS_SYSTEM_PROMPT = (
    "Your role as an assistant involves thorough exploration of questions through a "
    "systematic long thinking process before providing the final precise and accurate "
    "solutions. This requires engaging in a comprehensive cycle of analysis, "
    "summarizing, exploration, reassessment, reflection, backtracing and iteration to "
    "develop well-considered thinking process. Please structure your response into two "
    "main sections: Thought and Solution. In the Thought section, detail your reasoning "
    "process using the specified format: <think> {your thoughts} </think>. The Solution "
    "section should follow immediately after without additional labels."
)


def _normalize_text(text: str) -> str:
    """Trim and collapse excessive blank lines for stable serialization."""
    text = text.strip()
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


def _stable_hash_fraction(text: str) -> float:
    """Map a string deterministically to [0, 1) for split assignment.

    Uses MD5 so the train/val split is the same every run — no random seed needed.
    Identical to the function in convert_oasst2_to_jsonl.py.
    """
    digest = hashlib.md5(text.encode("utf-8")).hexdigest()
    value = int(digest[:8], 16)
    # Divide by 2**32 so range is [0, 1). Max 32-bit value never reaches 1.0.
    return value / 0x100000000


def _serialize_turns(
    system_text: str | None,
    turns: list[dict[str, str]],
) -> str:
    """Serialize system prompt + turns into role-tagged plain text for LM training.

    LRM note: The serialized format mirrors what the model sees during training:
      <|system|>
      {system prompt}
      <|user|>
      {question}
      <|assistant|>
      <think>
      {reasoning trace}
      </think>
      {final answer}

    The training loss mask is applied outside this function:
      - system/user content → mask = 0.0 (not supervised)
      - assistant content   → mask = 1.0 (supervised, including <think> block)

    Keeping <think>...</think> intact here is intentional. The model learns to
    generate the reasoning trace as part of the assistant response, not separately.
    """
    chunks: list[str] = []

    if system_text is not None:
        chunks.append(f"<|system|>\n{system_text}\n")

    for turn in turns:
        role = turn["role"]
        text = turn["text"]
        chunks.append(f"<|{role}|>\n{text}\n")

    return "".join(chunks)


def convert_openthoughts(
    out_dir: Path,
    val_ratio: float,
    max_samples_train: int,
    max_samples_val: int,
    min_chars: int,
    max_chars: int,
    include_system_prompt: bool,
) -> None:
    """Convert OpenThoughts-114k into JSONL train/val files.

    LRM note: We use the 'default' subset (114k rows) which is the verified,
    ready-to-train split used to train OpenThinker-7B and OpenThinker-32B.
    The 'metadata' subset has additional columns but is not needed here.
    """
    try:
        from datasets import load_dataset
    except ImportError as exc:
        raise ImportError(
            "This converter requires the 'datasets' package. "
            "Install with: pip install datasets"
        ) from exc

    print("Loading open-thoughts/OpenThoughts-114k (default split)...")
    dataset = load_dataset("open-thoughts/OpenThoughts-114k", split="train")
    print(f"  Loaded {len(dataset)} records.")

    out_dir.mkdir(parents=True, exist_ok=True)
    train_path = out_dir / "train.jsonl"
    val_path = out_dir / "val.jsonl"

    num_train = 0
    num_val = 0
    skipped = 0

    with train_path.open("w", encoding="utf-8") as train_file, val_path.open(
        "w", encoding="utf-8"
    ) as val_file:
        for record_idx, row in enumerate(dataset):
            if not isinstance(row, dict):
                skipped += 1
                continue

            # --- Extract system prompt (optional) ---
            system_raw = row.get("system", None)
            system_text: str | None = None
            if include_system_prompt and isinstance(system_raw, str):
                system_text = _normalize_text(system_raw)

            # --- Extract conversation turns ---
            conversations = row.get("conversations", [])
            if not isinstance(conversations, list) or len(conversations) < 2:
                skipped += 1
                continue

            turns: list[dict[str, str]] = []
            for conv in conversations:
                if not isinstance(conv, dict):
                    continue

                from_field = conv.get("from", "")
                value_field = conv.get("value", "")

                if not isinstance(from_field, str) or not isinstance(value_field, str):
                    continue

                # Map OpenThoughts role names to our standard roles.
                # LRM note: "human" is the question, "gpt" is the thinking+answer.
                from_lower = from_field.strip().lower()
                if from_lower in ("human", "user"):
                    role = ROLE_USER
                elif from_lower in ("gpt", "assistant", "model"):
                    role = ROLE_ASSISTANT
                else:
                    continue

                text = _normalize_text(value_field)
                if not text:
                    continue

                turns.append({"role": role, "text": text})

            if not turns:
                skipped += 1
                continue

            # Ensure conversation follows user → assistant pattern.
            if turns[0]["role"] != ROLE_USER or turns[-1]["role"] != ROLE_ASSISTANT:
                skipped += 1
                continue

            # --- Quality filter: check that assistant turn has a thinking trace ---
            # LRM note: Records without </think> in the assistant turn have
            # malformed or missing reasoning traces and are not useful for LRM training.
            assistant_text = turns[-1]["text"]
            has_thinking = "</think>" in assistant_text
            if not has_thinking:
                skipped += 1
                continue

            # --- Quality filter: overall text length ---
            serialized_text = _serialize_turns(system_text, turns)
            char_len = len(serialized_text)
            if not (min_chars <= char_len <= max_chars):
                skipped += 1
                continue

            # --- Deterministic train/val split via MD5 hash ---
            # Using the record index as the hash key gives a stable split
            # that is the same every run without needing a random seed.
            base_id = f"openthoughts_{record_idx:08d}"
            split_fraction = _stable_hash_fraction(base_id)
            split = "val" if split_fraction < val_ratio else "train"

            if split == "train" and num_train >= max_samples_train:
                continue
            if split == "val" and num_val >= max_samples_val:
                continue

            record = {
                "id": base_id,
                "source": "open-thoughts/OpenThoughts-114k",
                "split": split,
                "turns": turns,
                "serialized_text": serialized_text,
                "stats": {
                    "char_len": char_len,
                    "has_thinking": has_thinking,
                },
            }

            target_file = val_file if split == "val" else train_file
            target_file.write(json.dumps(record, ensure_ascii=False) + "\n")

            if split == "val":
                num_val += 1
            else:
                num_train += 1

            if (record_idx + 1) % 10_000 == 0:
                print(
                    f"  processed {record_idx + 1} records "
                    f"(train={num_train}, val={num_val}, skipped={skipped})"
                )

    print("\nOpenThoughts conversion complete.")
    print(f"  train records : {num_train}")
    print(f"  val records   : {num_val}")
    print(f"  skipped       : {skipped}")
    print(f"  output dir    : {out_dir}")
    print()
    print("Quick check — verify thinking tokens are present in train split:")
    print('  grep -m 1 "<think>" ' + str(train_path))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Convert open-thoughts/OpenThoughts-114k to JSONL reasoning corpus"
    )
    parser.add_argument(
        "--out-dir",
        type=str,
        default="data/openthoughts",
        help="Output directory for train.jsonl and val.jsonl",
    )
    parser.add_argument(
        "--val-ratio",
        type=float,
        default=0.05,
        help="Fraction of records assigned to the validation split",
    )
    parser.add_argument(
        "--min-chars",
        type=int,
        default=64,
        help="Minimum serialized text length (characters)",
    )
    parser.add_argument(
        "--max-chars",
        type=int,
        default=32_000,
        # LRM note: Reasoning traces are much longer than chat turns —
        # 32k chars is a reasonable upper bound to avoid truncation issues
        # while still excluding very noisy ultra-long records.
        help="Maximum serialized text length (characters)",
    )
    parser.add_argument(
        "--max-samples-train",
        type=int,
        default=200_000,
        help="Max records to write to train.jsonl",
    )
    parser.add_argument(
        "--max-samples-val",
        type=int,
        default=10_000,
        help="Max records to write to val.jsonl",
    )
    parser.add_argument(
        "--no-system-prompt",
        action="store_true",
        help=(
            "Omit the system prompt from serialized_text. "
            "By default the system prompt is included because the model was "
            "trained on it and uses it to enter reasoning mode."
        ),
    )
    return parser


if __name__ == "__main__":
    args = build_parser().parse_args()
    convert_openthoughts(
        out_dir=Path(args.out_dir),
        val_ratio=args.val_ratio,
        max_samples_train=args.max_samples_train,
        max_samples_val=args.max_samples_val,
        min_chars=args.min_chars,
        max_chars=args.max_chars,
        include_system_prompt=not args.no_system_prompt,
    )
